Repository woowacourse-study/2022-book-muscle, pull requests merged in 2022-03, with the labels that each got.

#22 [자스민 3.1] 딥다이브 ch12(p154 ~ p168)
  modern-javascript-deep-dive/jasmin/asset/함수선언문_동작.png
  modern-javascript-deep-dive/jasmin/ch12_function.md
Labels: 화요일

#21 [마르코 3.1] 딥다이브 ch25 클래스 (p.436~p.446)
  modern-javascript-deep-dive/marco/ch25_class.md
Labels: 화요일

#29 [동키콩 3.2] 리팩터링 ch06. 기본적인 리팩터링
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.1 함수 추출하기.md
Labels: 수요일, 리팩토링

#25 [준찌 3.2] 딥다이브 ch19 프로토타입 완 (p 280 ~ p 312)
  modern-javascript-deep-dive/juunzzi/ch19_prototype.md
  modern-javascript-deep-dive/juunzzi/ch22_this.md
Labels: 수요일, 딥다이브

#27 [후이 3.2] 딥다이브 ch12 함수(p.166 ~ p.177)
  modern-javascript-deep-dive/hui/ch12_함수.md
Labels: 수요일, 딥다이브

#31 [마르코 3.2] 딥다이브 ch25 클래스 (p.447~p.468)
  modern-javascript-deep-dive/marco/ch25_class.md
Labels: 수요일, 딥다이브

#24 [록바 3.2] 딥다이브 ch10 객체 리터럴 (p.124 ~ p.136)
  modern-javascript-deep-dive/lokba/ch04_variable.md
  modern-javascript-deep-dive/lokba/ch10_object_literal.md
Labels: 수요일, 딥다이브

#28 [온스타 3.2] 코어자바스크립트 ch3 this (p.86~p.103)
  core-javascript/onstar/ch03_this.md
Labels: 수요일, 코어JS

#30 [빅터 3.2] 딥다이브 ch05 표현식과 문(p.55 ~ p.58), ch06 데이터 타입(p.59 ~ p.64)
  modern-javascript-deep-dive/victor/ch05_expression_and_statement.md
  modern-javascript-deep-dive/victor/ch06_data_type.md
Labels: 수요일, 딥다이브

#35 [빅터 3.4] 딥다이브 ch06 데이터 타입(p.65 ~ p.73), ch07 연산자 (p.74 ~ p.92)
  modern-javascript-deep-dive/victor/ch06_data_type.md
  modern-javascript-deep-dive/victor/ch07_operator.md
Labels: 딥다이브, 목요일

#36 [온스타 3.3] 코어자바스크립트 ch4 콜백 함수 (p.104~p.113)
  core-javascript/onstar/ch04_call-back.md
Labels: 코어JS, 목요일

#33 [동키콩 3.3] 리팩터링 06.기본적인 리팩터링 6.2,6.3(p.169~p.178)
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.2 함수 인라인하기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.3 변수 추출하기.md
Labels: 리팩토링, 목요일

#32 [준찌 3.3] 딥다이브 ch22 this (p342 ~ p358)
  modern-javascript-deep-dive/juunzzi/ch22_this(자기참조변수).md
Labels: 딥다이브, 목요일

#38 [자스민 3.4] 딥다이브 ch13스코프(p189 ~ 198)
  modern-javascript-deep-dive/jasmin/asset/scope.png
  modern-javascript-deep-dive/jasmin/ch13_scope.md
  modern-javascript-deep-dive/jasmin/ch18_function_and_first_class_object.md
Labels: 딥다이브, 금요일

#41 [준찌 3.4] 딥다이브 ch23 실행컨텍스트 (p.359 ~ p.366)
  modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
Labels: 딥다이브, 금요일

#37 [온스타 3.4] 코어자바스크립트 ch4 콜백 함수 (p.114~p.124)
  core-javascript/onstar/ch04_call-back-tmp.md
Labels: 코어JS, 금요일

#34 [후이 3.4] 딥다이브 ch 12 함수 (p.177 ~ p.188)
  modern-javascript-deep-dive/hui/ch12_함수.md
Labels: 딥다이브, 목요일

#40 [마르코 3.4] You don't know JS, part2 ch1 스코프(p.193~p.204)
  you-dont-know-js/marco/part2-ch1_scope.md
Labels: 금요일, 유돈노제이에스

#42 [록바 3.5] 딥다이브 ch11 원시 값과 객체의 비교 (p.137 ~ p.153)
  modern-javascript-deep-dive/lokba/ch11_primitive_vs_object.md
  modern-javascript-deep-dive/lokba/img/object_copy.png
  modern-javascript-deep-dive/lokba/img/object_mutable_1.png
  modern-javascript-deep-dive/lokba/img/object_mutable_2.png
  modern-javascript-deep-dive/lokba/img/primitive_copy.png
  modern-javascript-deep-dive/lokba/img/primitive_immutable.png
Labels: 딥다이브, 토요일

#43 [자스민 3.6]ch13, ch14(p198 ~ p207)
  modern-javascript-deep-dive/jasmin/asset/letvar.png
  modern-javascript-deep-dive/jasmin/asset/지역변수의 생명주기.png
  modern-javascript-deep-dive/jasmin/ch13_scope.md
  modern-javascript-deep-dive/jasmin/ch14_global_variable_problem.md
  modern-javascript-deep-dive/jasmin/ch15_let_const_bloack_scope.md
Labels: 딥다이브, 토요일

#48 [후이 3.6] 딥다이브 ch13 스코프 (p.189 ~ 199)
  modern-javascript-deep-dive/hui/ch13_스코프.md
Labels: 딥다이브

#49 [후이 3.7] 딥다이브 ch14,ch15 (p.200 ~ 207)
  modern-javascript-deep-dive/hui/ch14_전역변수의_문제점.md
  modern-javascript-deep-dive/hui/ch15_let_const_block_level_scope.md
Labels: 딥다이브

#47 [자스민 3.6] 딥다이브 ch15(p208 ~ 218)
  modern-javascript-deep-dive/jasmin/asset/function_prototype.png
  modern-javascript-deep-dive/jasmin/asset/prototype_chain.png
  modern-javascript-deep-dive/jasmin/asset/스크린샷 2022-03-15 오후 3.58.59.png
  modern-javascript-deep-dive/jasmin/ch15_let_const_block_scope.temp.md
  modern-javascript-deep-dive/jasmin/ch19_prototype.md
Labels: 딥다이브

#54 [마르코 3.15] 딥다이브 ch45 프로미스(842~869)
  modern-javascript-deep-dive/marco/ch45_promise.md
Labels: 화요일, 딥다이브

#45 [동키콩 3.6] 리팩터링 06. 기본적인 리팩터링 6.4,6.5(p.178~p.187)
  .DS_Store
  refactoring/.DS_Store
  refactoring/donkeykong/.DS_Store
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.4 변수 인라인하기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.5 함수 선언 바꾸기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.6 변수 캡슐화하기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.7 변수 이름 바꾸기.md
Labels: 리팩토링, 토요일

#57 [마르코 3.16] 딥다이브 ch46 제너레이터와 async/await(870~885)
  modern-javascript-deep-dive/marco/ch46_generator-async-await.md
  you-dont-know-js/marco/스코프와 클로저/ch1_scope-closure.md
Labels: 수요일, 딥다이브

#59 [준찌 3.17] 실행컨텍스트 P366 ~ P387
  modern-javascript-deep-dive/juunzzi/assets/.keep
  modern-javascript-deep-dive/juunzzi/assets/실행컨텍스트.png
  modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
Labels: 딥다이브, 목요일

#61 [후이 3.17] 딥다이브 ch 22 this (p.342 ~ 358)
  modern-javascript-deep-dive/hui/ch22_this.md
Labels: 딥다이브, 목요일

#56 [빅터 3.15] 딥다이브 ch12 함수(p.154 ~ 188)
  modern-javascript-deep-dive/victor/ch12_function.md
Labels: 화요일, 딥다이브

#60 [록바 3.17] 딥다이브 ch12 함수(p.154 ~ p.163)
  modern-javascript-deep-dive/lokba/ch12_function.md
Labels: 딥다이브, 목요일

#55 [자스민 3.15] 딥다이브 프로토타입(p259 ~ 272)
  modern-javascript-deep-dive/jasmin/ch19_prototype_copy.md
Labels: 화요일, 딥다이브

#62 [마르코 3.17] You don't know JS 1장-비동기성 (177~204)
  modern-javascript-deep-dive/marco/ch41_timer.md
  you-dont-know-js/marco/비동기와 성능/ch1_asynchronous.md
Labels: 목요일, You don't know JS

#53 [온스타 3.15] 코어자바스크립트 ch5 클로저 (p.115~p.125)
  core-javascript/onstar/ch02_execution-context.md
  core-javascript/onstar/ch04_call-back-tmp.md
  core-javascript/onstar/ch05_closure.md
Labels: 화요일, 코어JS

#65 [자스민 3.18] 딥다이브 ch19(p272 ~ p284)
  modern-javascript-deep-dive/jasmin/ch19_prototype.md
Labels: 딥다이브, 금요일

#69 [자스민 3.19] 딥다이브 ch19(p284 ~ p302)
  modern-javascript-deep-dive/jasmin/asset/스크린샷 2022-03-19 오후 11.09.07.png
  modern-javascript-deep-dive/jasmin/asset/스크린샷 2022-03-19 오후 5.11.05.png
  modern-javascript-deep-dive/jasmin/asset/스크린샷 2022-03-19 오후 6.07.58.png
  modern-javascript-deep-dive/jasmin/asset/스크린샷 2022-03-20 오전 12.00.18.png
  modern-javascript-deep-dive/jasmin/ch19_prototype.md
Labels: 딥다이브, 토요일

#64 [빅터 3.18] 딥다이브 ch18 함수와 일급 객체(p.249 ~ 258)
  modern-javascript-deep-dive/victor/ch18_function_and_first_class_object.md
Labels: 딥다이브, 금요일

#70 [자스민 3.20] 딥다이브 ch19 (p303 ~ p312)
  modern-javascript-deep-dive/jasmin/ch19_prototype.md
Labels: 딥다이브

#71 [후이 3.21] 딥다이브 ch26 ES6 함수의 추가 기능 (p 469 ~ 491)
  modern-javascript-deep-dive/hui/ch26_ES6.md
Labels: 월요일, 딥다이브

#66 [준찌 3.18] 딥다이브 ch19(p386 ~ p401)
  modern-javascript-deep-dive/juunzzi/assets/inner.jpeg
  modern-javascript-deep-dive/juunzzi/assets/렉시컬환경과 클로저.jpeg
  modern-javascript-deep-dive/juunzzi/assets/블록 레벨 스코프 이후.png
  modern-javascript-deep-dive/juunzzi/assets/블록 레벨 스코프.png
  modern-javascript-deep-dive/juunzzi/assets/함수객체와렉시컬환경.jpeg
  modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
  modern-javascript-deep-dive/juunzzi/ch24_클로저.md
Labels: 딥다이브, 금요일

#68 [온스타 3.19] 코어자바스크립트 ch5 클로저 (p.126~p.145)
  core-javascript/onstar/ch05_closure_tmp.md
Labels: 코어JS, 토요일

#73 [마르코 3.26] 객체지향의 사실과 오해(1장~4장) p1~137
  modern-javascript-deep-dive/marco/ch18_함수와 일급객체.md
  modern-javascript-deep-dive/marco/img/일급객체.png
  you-dont-know-js/marco/this와 객체 프로토타입/ch1_this-or-that.md
  객체지향의사실과오해/marco/ch01-ch04.md
Labels: 토요일, 객체지향의 사실과 오해

#74 [록바 3.27] 딥다이브 ch12 함수(p.163 ~ p.188) + [록바 3.29] 딥다이브 ch13 스코프(p.189 ~ p.199)
  modern-javascript-deep-dive/lokba/ch12_function.md
  modern-javascript-deep-dive/lokba/ch13_scope.md
Labels: 화요일, 딥다이브, 일요일

#67 [동키콩 3.18] 리팩터링 6.8.매개변수 객체만들기, 6.9 여러함수를 클래스로 묶기(p197 ~ p207)
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.10 여러 함수를 변환 함수로 묶기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.11 단계 쪼개기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.8 매개변수 객체 만들기.md
  refactoring/donkeykong/ch06.기본적인 리팩터링/6.9 여러 함수를 클래스로 묶기.md
Labels: 리팩토링, 토요일
